use anyhow::Result;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

pub fn generate(out: Option<PathBuf>) -> Result<()> {
    let workspace = crate::workspace::require_workspace()?;
    let engagement = crate::engagement::storage::load_engagement()?;
    let scope = crate::scope::commands::load_store()?;
    let assets = crate::assets::commands::load_store()?;
    let findings = crate::findings::commands::load_all()?;
    let evidence = crate::evidence::commands::load_all()?;
    let timeline = crate::timeline::commands::load_all()?;

    let mut body = String::new();

    writeln!(body, "# {}", engagement.name)?;
    writeln!(body)?;
    writeln!(body, "Generated by redtrace.")?;
    writeln!(body)?;

    writeln!(body, "## 1. Executive Summary")?;
    writeln!(body)?;
    writeln!(body, "This report summarizes an authorized security assessment tracked through redtrace. It includes scope, assets, findings, evidence integrity metadata, timeline entries, and defensive remediation guidance.")?;
    writeln!(body)?;

    writeln!(body, "## 2. Scope and Rules of Engagement")?;
    writeln!(body)?;
    if let Some(client) = engagement.client.as_ref() {
        writeln!(body, "**Client:** {client}")?;
        writeln!(body)?;
    }
    if let Some(roe) = engagement.rules_of_engagement.as_ref() {
        writeln!(body, "**Rules of Engagement:** {roe}")?;
    } else {
        writeln!(body, "**Rules of Engagement:** Not documented in redtrace.")?;
    }
    writeln!(body)?;
    writeln!(body, "### Scope Rules")?;
    writeln!(body)?;
    writeln!(body, "| ID | Type | Value | Label |")?;
    writeln!(body, "|---|---|---|---|")?;
    for rule in &scope.rules {
        writeln!(body, "| {} | {:?} | `{}` | {} |", rule.id, rule.rule_type, rule.value, rule.label.clone().unwrap_or_default())?;
    }
    writeln!(body)?;
    writeln!(body, "### Exclusions")?;
    writeln!(body)?;
    writeln!(body, "| ID | Type | Value | Reason |")?;
    writeln!(body, "|---|---|---|---|")?;
    for exclusion in &scope.exclusions {
        writeln!(body, "| {} | {:?} | `{}` | {} |", exclusion.id, exclusion.rule_type, exclusion.value, exclusion.reason)?;
    }
    writeln!(body)?;

    writeln!(body, "## 3. Methodology")?;
    writeln!(body)?;
    writeln!(body, "The engagement data was organized around authorized scope, asset inventory, observed findings, evidence artifacts, timeline entries, and security-control remediation. redtrace does not execute offensive actions; it records and structures operator output.")?;
    writeln!(body)?;

    writeln!(body, "## 4. Asset Summary")?;
    writeln!(body)?;
    writeln!(body, "| ID | Hostname | IP | Type | Scope Status | Tags |")?;
    writeln!(body, "|---|---|---|---|---|---|")?;
    for asset in &assets.assets {
        writeln!(body, "| {} | {} | {} | {} | {} | {} |", asset.id, asset.hostname, asset.ip.clone().unwrap_or_default(), asset.asset_type, asset.scope_status, asset.tags.join(", "))?;
    }
    writeln!(body)?;

    writeln!(body, "## 5. Timeline")?;
    writeln!(body)?;
    writeln!(body, "| Time | Reference | Event |")?;
    writeln!(body, "|---|---|---|")?;
    for event in &timeline {
        writeln!(body, "| {} | {} | {} |", event.time, event.ref_id.clone().unwrap_or_else(|| "-".to_string()), event.event)?;
    }
    writeln!(body)?;

    writeln!(body, "## 6. Findings Overview")?;
    writeln!(body)?;
    writeln!(body, "| ID | Title | Severity | Status | Assets | Evidence |")?;
    writeln!(body, "|---|---|---|---|---|---|")?;
    for finding in &findings {
        let severity = finding.severity.as_ref().map(|severity| severity.to_string()).unwrap_or_else(|| "Unrated".to_string());
        writeln!(body, "| {} | {} | {} | {} | {} | {} |", finding.id, finding.title, severity, finding.status, finding.asset_ids.join(", "), finding.evidence_ids.len())?;
    }
    writeln!(body)?;

    writeln!(body, "## 7. Detailed Findings")?;
    writeln!(body)?;
    for finding in &findings {
        let severity = finding.severity.as_ref().map(|severity| severity.to_string()).unwrap_or_else(|| "Unrated".to_string());
        writeln!(body, "### {} — {}", finding.id, finding.title)?;
        writeln!(body)?;
        writeln!(body, "**Severity:** {severity}  ")?;
        writeln!(body, "**Status:** {}  ", finding.status)?;
        writeln!(body, "**Affected Assets:** {}  ", display_or_dash(&finding.asset_ids))?;
        writeln!(body, "**Confidence:** {}  ", finding.confidence.as_ref().map(|confidence| confidence.to_string()).unwrap_or_else(|| "Unset".to_string()))?;
        writeln!(body)?;
        writeln!(body, "#### Summary")?;
        writeln!(body)?;
        writeln!(body, "{}", finding.summary.as_deref().unwrap_or("Not documented."))?;
        writeln!(body)?;
        writeln!(body, "#### Impact")?;
        writeln!(body)?;
        writeln!(body, "{}", finding.impact.as_deref().unwrap_or("Not documented."))?;
        writeln!(body)?;
        writeln!(body, "#### Evidence")?;
        writeln!(body)?;
        if finding.evidence_ids.is_empty() {
            writeln!(body, "No evidence linked.")?;
        } else {
            for evidence_id in &finding.evidence_ids {
                if let Some(item) = evidence.iter().find(|item| &item.id == evidence_id) {
                    writeln!(body, "- {} — {}, SHA-256 `{}`", item.id, item.evidence_type, item.sha256)?;
                } else {
                    writeln!(body, "- {evidence_id} — metadata missing")?;
                }
            }
        }
        writeln!(body)?;
        writeln!(body, "#### Mapping")?;
        writeln!(body)?;
        if finding.attack_mappings.is_empty() && finding.owasp_mappings.is_empty() && finding.csf_mappings.is_empty() {
            writeln!(body, "No mappings documented.")?;
        } else {
            for mapping in &finding.attack_mappings {
                writeln!(body, "- MITRE ATT&CK: {} / {}", mapping.tactic, mapping.technique)?;
            }
            for mapping in &finding.owasp_mappings {
                writeln!(body, "- OWASP WSTG: {mapping}")?;
            }
            for mapping in &finding.csf_mappings {
                writeln!(body, "- NIST CSF: {mapping}")?;
            }
        }
        writeln!(body)?;
        writeln!(body, "#### Recommendation")?;
        writeln!(body)?;
        writeln!(body, "{}", finding.recommendation.as_deref().unwrap_or("Not documented."))?;
        writeln!(body)?;
    }

    writeln!(body, "## 8. Evidence Index")?;
    writeln!(body)?;
    writeln!(body, "| ID | Type | Original Filename | Stored Path | SHA-256 |")?;
    writeln!(body, "|---|---|---|---|---|")?;
    for item in &evidence {
        writeln!(body, "| {} | {} | {} | `{}` | `{}` |", item.id, item.evidence_type, item.original_filename, item.stored_path.display(), item.sha256)?;
    }
    writeln!(body)?;

    writeln!(body, "## 9. MITRE ATT&CK Mapping")?;
    writeln!(body)?;
    writeln!(body, "| Finding | Tactic | Technique |")?;
    writeln!(body, "|---|---|---|")?;
    for finding in &findings {
        for mapping in &finding.attack_mappings {
            writeln!(body, "| {} | {} | {} |", finding.id, mapping.tactic, mapping.technique)?;
        }
    }
    writeln!(body)?;

    writeln!(body, "## 10. OWASP WSTG Mapping")?;
    writeln!(body)?;
    writeln!(body, "| Finding | OWASP WSTG ID |")?;
    writeln!(body, "|---|---|")?;
    for finding in &findings {
        for mapping in &finding.owasp_mappings {
            writeln!(body, "| {} | {} |", finding.id, mapping)?;
        }
    }
    writeln!(body)?;

    writeln!(body, "## 11. NIST CSF Defensive Outcomes")?;
    writeln!(body)?;
    writeln!(body, "| Finding | CSF Function |")?;
    writeln!(body, "|---|---|")?;
    for finding in &findings {
        for mapping in &finding.csf_mappings {
            writeln!(body, "| {} | {} |", finding.id, mapping)?;
        }
    }
    writeln!(body)?;

    writeln!(body, "## 12. Remediation Roadmap")?;
    writeln!(body)?;
    writeln!(body, "Prioritize confirmed high-impact issues first, then medium-risk systemic weaknesses, then low-risk hardening tasks. Validate remediation with repeat evidence and update finding status.")?;
    writeln!(body)?;

    writeln!(body, "## 13. Appendix")?;
    writeln!(body)?;
    writeln!(body, "This report was generated from the local redtrace workspace. Evidence hashes are included for integrity verification.")?;

    let out = out.unwrap_or_else(|| workspace.join("reports").join("report.md"));
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&out, body)?;
    println!("generated Markdown report at {}", out.display());
    Ok(())
}

fn display_or_dash(values: &[String]) -> String {
    if values.is_empty() {
        "-".to_string()
    } else {
        values.join(", ")
    }
}
